authors:
  admin:
    name: AI Resources Team
    description: Core team maintaining AI Resources
    avatar: https://github.com/nitin27may.png
  
  nitin:
    name: Nitin Kumar Singh
    description: AI & Cloud Architecture Specialist
    avatar: https://avatars.githubusercontent.com/u/8065536?s=400&u=e69755794612e29edb12c965f5c93f125c9c6996&v=4
    url: https://github.com/nitin27may
